Vagrant.configure("2") do |config|

  config.vm.define "merkur-server-vm" do |msvm|
    msvm.vm.box = "merkur-server-vm"
    msvm.vm.hostname = "merkur-server-vm"
    msvm.vm.network "private_network", ip: "192.168.50.190"
    msvm.vm.network :forwarded_port, host:7777, guest:80
    msvm.vm.network :forwarded_port, host:8888, guest:15672
    msvm.vm.network :forwarded_port, host:8080, guest:8080
  end

  config.vm.define "merkur-client-1-vm" do |mcvm1|
    mcvm1.vm.box = "merkur-client-1-vm"
    mcvm1.vm.hostname = "merkur-client-1-vm"
    mcvm1.vm.network "private_network", ip: "192.168.50.191"
  end

  config.vm.define "merkur-client-2-vm" do |mcvm2|
    mcvm2.vm.box = "merkur-client-2-vm"
    mcvm2.vm.hostname = "merkur-client-2-vm"
    mcvm2.vm.network "private_network", ip: "192.168.50.192"
  end
  
end
